### PR TITLE
Evaluation module: Version 0.2.0

### PR DESCRIPTION
**Pull request by faroit**
Lets remove the last step to a matlab-free source separation
- [x] Include mir_eval.separation.framewise module #10 
- [x] write out proper pandas dataframes
- [x] create import and export methods
- [x] add new unit tests #11

### CODE REVIEW

**Comment by carlthome** [comment]
Status? Would be nice to be able to solely rely on dsdtools for framewise SDR, SIR, SAR calculation as I enjoy the clean API.

**Comment by faroit** [comment]
we are working hard on making this possible. Stay tuned... sisec call for participation starts next week

**Comment by carlthome** [comment]
Nice! I'm looking to make a SiSEC submission, hence my question. :smile:

**Comment by faroit** [comment]
This PR will be closed because the evaluation package will be moved to a separate package. The evaluation package is in the works and will be released this year.

@carlthome the sisec call is out. So is a new python parser. See [here](https://github.com/sigsep/sigsep-mus-db)

**Pull request closed without merging**
